### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by jcosmo** [replicant4j/replicant#4]
`
[#|2017-10-03T10:00:23.156+1100|SEVERE|Payara 4.1|javax.enterprise.web|_ThreadID=27;_ThreadName=http-thread-pool::http-listener-1(4);_TimeMillis=1506985223156;_LevelValue=1000;|WebModule[/calendar]Exception while dispatching incoming RPC call
com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract void iris.calendar.shared.service.gwt_api.GwtRpcCalendarService.unsubscribeFromResources(java.lang.String,java.util.List) throws iris.calendar.shared.data_type.gwt_api.GwtRpcNoSuchSessionException' threw an unexpected exception: java.util.ConcurrentModificationException
        at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:416)
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
        at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
        at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1696)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:318)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
        at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:416)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:283)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:466)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:169)
        at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:206)
        at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:180)
        at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
        at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
        at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
        at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
        at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:526)
        at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
        at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
        at java.util.AbstractCollection.toArray(AbstractCollection.java:141)
        at java.util.Collections$UnmodifiableCollection.toArray(Collections.java:1033)
        at java.util.ArrayList.<init>(ArrayList.java:177)
        at org.realityforge.replicant.server.transport.ReplicantSessionManagerImpl.performUnsubscribe(ReplicantSessionManagerImpl.java:706)
        at iris.calendar.server.net.CalendarReplicantPollService$CalendarSubscriptionService$EntityMessageEndpoint$ReplicantSessionManager$SessionManager$698885300$Proxy$_$$_WeldSubclass.performUnsubscribe(Unknown Source)
        at org.realityforge.replicant.server.transport.ReplicantSessionManagerImpl.unsubscribe(ReplicantSessionManagerImpl.java:678)
        at iris.calendar.server.net.CalendarReplicantPollService$CalendarSubscriptionService$EntityMessageEndpoint$ReplicantSessionManager$SessionManager$698885300$Proxy$_$$_WeldSubclass.unsubscribe(Unknown Source)
        at org.realityforge.replicant.server.transport.ReplicantSessionManagerImpl.bulkUnsubscribe(ReplicantSessionManagerImpl.java:690)
        at iris.calendar.server.net.CalendarReplicantPollService$CalendarSubscriptionService$EntityMessageEndpoint$ReplicantSessionManager$SessionManager$698885300$Proxy$_$$_WeldSubclass.bulkUnsubscribe(Unknown Source)
        at org.realityforge.replicant.server.transport.ReplicantSessionManagerImpl.bulkUnsubscribe(ReplicantSessionManagerImpl.java:667)
        at iris.calendar.server.net.CalendarReplicantPollService$CalendarSubscriptionService$EntityMessageEndpoint$ReplicantSessionManager$SessionManager$698885300$Proxy$_$$_WeldSubclass.bulkUnsubscribe(Unknown Source)
        at iris.calendar.server.net.CalendarSessionManagerImpl.unsubscribeFromMultipleResources(CalendarSessionManagerImpl.java:325)
        at iris.calendar.server.net.CalendarReplicantPollService$CalendarSubscriptionService$EntityMessageEndpoint$ReplicantSessionManager$SessionManager$698885300$Proxy$_$$_WeldSubclass.unsubscribeFromMultipleResources$$super(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:49)
        at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:77)
        at org.glassfish.jersey.ext.cdi1x.transaction.internal.WebAppExceptionInterceptor.intercept(WebAppExceptionInterceptor.java:77)
        at sun.reflect.GeneratedMethodAccessor156.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
        at org.jboss.weld.interceptor.proxy.NonTerminalAroundInvokeInvocationContext.proceedInternal(NonTerminalAroundInvokeInvocationContext.java:64)
        at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:77)
        at org.glassfish.cdi.transaction.TransactionalInterceptorBase.proceed(TransactionalInterceptorBase.java:228)
        at org.glassfish.cdi.transaction.TransactionalInterceptorRequired.transactional(TransactionalInterceptorRequired.java:103)
        at sun.reflect.GeneratedMethodAccessor155.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84)
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72)
        at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56)
        at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79)
        at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68)
        at iris.calendar.server.net.CalendarReplicantPollService$CalendarSubscriptionService$EntityMessageEndpoint$ReplicantSessionManager$SessionManager$698885300$Proxy$_$$_WeldSubclass.unsubscribeFromMultipleResources(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
        at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:100)
        at org.realityforge.replicant.server.CalendarReplicantPollService$CalendarSubscriptionService$EntityMessageEndpoint$ReplicantSessionManager$SessionManager$698885300$Proxy$_$$_WeldClientProxy.unsubscribeFromMultipleResources(Unknown Source)
        at iris.calendar.server.service.gwt_api.CalendarServiceImpl.unsubscribeFromResources(CalendarServiceImpl.java:84)
        at iris.calendar.server.service.gwt_api.CalendarService$1375786197$Proxy$_$$_WeldSubclass.unsubscribeFromResources$$super(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

`

**Comment by realityforge** [comment]
Fixed in `v6.74`
